// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHd5kCXHHhg26Fhe6-lxF-Bpj4UscMPNQ',
    appId: '1:590626578288:web:fa6533f3b153417a',
    messagingSenderId: '590626578288',
    projectId: 'pecbr-f37f0',
    authDomain: 'pecbr-f37f0.firebaseapp.com',
    databaseURL: 'https://pecbr-f37f0.firebaseio.com',
    storageBucket: 'pecbr-f37f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl0FiYc4KMObY7AnsAXFJ6c_D11-Z1J1g',
    appId: '1:590626578288:android:c3da14462a5bd0378179b5',
    messagingSenderId: '590626578288',
    projectId: 'pecbr-f37f0',
    databaseURL: 'https://pecbr-f37f0.firebaseio.com',
    storageBucket: 'pecbr-f37f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPlrQ867vyNJ4JqN-uB47nxxtEFuk9-JU',
    appId: '1:590626578288:ios:fd1b89efee4831968179b5',
    messagingSenderId: '590626578288',
    projectId: 'pecbr-f37f0',
    databaseURL: 'https://pecbr-f37f0.firebaseio.com',
    storageBucket: 'pecbr-f37f0.appspot.com',
    androidClientId: '590626578288-nahbhupd8gvc2asttvh4u8knofumadu2.apps.googleusercontent.com',
    iosClientId: '590626578288-s8eoes6flta29ve6o62jq4tlr0q3a4k3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pecbrPecuaristaApp',
  );
}
